### ISSUE TITLE
Support for C#6.0

### ISSUE THREAD

**Issue by kahgeh** [getgauge/gauge-csharp#51]
this line- public List<User> Users { get; } = new List<User>();

is throwing this error :
  error CS1519: Invalid token '=' in class, struct, or interface member declaration

**Comment by sriv** [comment]
This would require using MSBuild 14.0 for compiling the code. And it seems that `Microsoft.Build` namespace that we use, would require users to have .NET framework 4.6 installed.

Not sure if Gauge-CSharp can mandate .NET 4.6 as a pre-requisite (yet?).

**Comment by WonkiDonk** [comment]
@kahgeh the Visual Studio plug-in supports C# 6. The plug-in uses Visual Studio to compile the code and then passes a reference to the compiled code to Gauge for test execution. If you're using a version of Visual Studio that supports C# 6 then this will work fine.

For CI scenarios where you need to execute the tests at the command line, my team uses the following work-around. Hopefully official support will come soon. Failing that, you could always fork the code and enable it for your team yourself :)

## Workaround for Command Line/CI

1. Build code using msbuild.
2. Define environment variable: `gauge_custom_build_path` with the location of the compiled code.
3. Run gauge for the specs you want to execute.

This is exactly what the Visual Studio plug-in does [GaugeRunner.cs:54](https://github.com/getgauge/gauge-visualstudio/blob/8f239d8055ee441b005f27483c3b206a29644278/Gauge.VisualStudio.TestAdapter/GaugeRunner.cs). Let me know if you have any issues.

**Comment by sriv** [comment]
@WonkiDonk - thanks for sharing the workaround. I'll try to elaborate why we haven't done anything about this yet.

Gauge-CSharp [tries to compile](https://github.com/getgauge/gauge-csharp/blob/master/Runner/GaugeProjectBuilder.cs#L37) the csharp test code using the `Microsoft.Build` namespace APIs. This is because we get more control than invoking `msbuild.exe` as a `Process`. Hence, for C# 6 we need to upgrade `Microsoft.Build` to v14.0, which AFAIK would make .NET 4.6 as a requirement for Gauge-CSharp.

I was told by a few users that .NET 4.6 was not yet available in their environments (company policies), and since this clearly would break on lesser versions, we decided to wait till .NET 4.6 becomes a bit more mainstream.

**Comment by Christoffer-Green** [comment]
Any updates or thoughs on this now that .NET 4.6 is more mainstream?

**Comment by sriv** [comment]
Yes, thanks for reminding. Its about time we did this.

**Comment by todorinskiz** [comment]
Hi @sriv , 

I have managed to upgrade the Microsoft.Build references to ToolsVersion 15.0. It seems to build the project just fine, but then it reaches SandboxBuilder.Build() and it seems that Guage.CSharp.Runner assembly is not loaded in the Sandbox domain, therefore Sandbox type that is located in that assembly is not found and the SandboxBuilder.Build() method returns null sandbox. 

I tried using the assembly resolver principle to resolve the the missing assemblies, but the method cannot be discovered once serialized/deserialized. (SandboxBuilder is serializeable).

Can you point me into some direction so we can move forward? Otherwise Gauge will not be suitable for our project.

Regards,
Zlatin

**Comment by sriv** [comment]
@todorinskiz - thanks for taking a stab at this. I will look into this this week (I now have access to a windows machine).

Is there someway I can look at your changes please? Thanks.

**Comment by sriv** [comment]
An update, I realized that we use `Fake`'s `MSBuildHelper` to build the user's project if user is working on Mono. And that worked fine with C# 6.0

And there is no reason why it wouldn't work on Windows + .NET Framework!

So, in interest of being consistent, gauge-csharp now uses `Fake`'s helper to build user code on all platforms (via e2ea251). This should allow you to use C# 6.0 (or perhaps even 7.0)

Please try and pass on any feedback.

**Comment by HakunnaMatata** [comment]
Hi @sriv,

can you write a comment about how do i use gauge with c# 6/.net 4.6+ ?
i tried few things with no success.

when i'm executing "_gauge run specs_" from powershell I get the next response.

_StepImplementation.cs(49,40): error CS1056: Unexpected character '$'
Done building project "GaugePoc.csproj" -- FAILED.
Failed to start gauge API: Timed out connecting to [::]:50153_


thanks for your help!

**Comment by sriv** [comment]
An update: gauge-csharp v0.10.2 is released and should allow you to use c# 6.0 without having to build outside gauge.
